package me.vrekt.fortnitexmpp.party.implementation.member.emoji;

public enum Emoji {

    Emoji_100APlus("Emoji_100APlus"),
    Emoji_1HP("Emoji_1HP"),
    Emoji_200IQPlay("Emoji_200IQPlay"),
    Emoji_Ace("Emoji_Ace"),
    Emoji_Alarm("Emoji_Alarm"),
    Emoji_Angel("Emoji_Angel"),
    Emoji_APlus("Emoji_APlus"),
    Emoji_ArmFlex("Emoji_ArmFlex"),
    Emoji_Awww("Emoji_Awww"),
    Emoji_BabySeal("Emoji_BabySeal"),
    Emoji_BadApple("Emoji_BadApple"),
    Emoji_Baited("Emoji_Baited"),
    Emoji_Banana("Emoji_Banana"),
    Emoji_Bang("Emoji_Bang"),
    Emoji_BattleBus("Emoji_BattleBus"),
    Emoji_Birthday2018("Emoji_Birthday2018"),
    Emoji_BlackCat("Emoji_BlackCat"),
    Emoji_BobWhat("Emoji_BobWhat"),
    Emoji_Boombox("Emoji_Boombox"),
    Emoji_Bullseye("Emoji_Bullseye"),
    Emoji_Bush("Emoji_Bush"),
    Emoji_Camera("Emoji_Camera"),
    Emoji_Camper("Emoji_Camper"),
    Emoji_Celebrate("Emoji_Celebrate"),
    Emoji_Chicken("Emoji_Chicken"),
    Emoji_Clapping("Emoji_Clapping"),
    Emoji_Clown("Emoji_Clown"),
    Emoji_Comm("Emoji_Comm"),
    Emoji_Crabby("Emoji_Crabby"),
    Emoji_DealWithIt("Emoji_DealWithIt"),
    Emoji_Disco("Emoji_Disco"),
    Emoji_DurrrBurger("Emoji_DurrrBurger"),
    Emoji_Dynamite("Emoji_Dynamite"),
    Emoji_Embarrassed("Emoji_Embarrassed"),
    Emoji_Exclamation("Emoji_Exclamation"),
    Emoji_Explosion("Emoji_Explosion"),
    Emoji_Fiery("Emoji_Fiery"),
    Emoji_FistBump("Emoji_FistBump"),
    Emoji_FKey("Emoji_FKey"),
    Emoji_FlamingRage("Emoji_FlamingRage"),
    Emoji_FoamFinger("Emoji_FoamFinger"),
    Emoji_GG("Emoji_GG"),
    Emoji_GGWreath("Emoji_GGWreath"),
    Emoji_Ghost("Emoji_Ghost"),
    Emoji_GingerbreadHappy("Emoji_GingerbreadHappy"),
    Emoji_GingerbreadMad("Emoji_GingerbreadMad"),
    Emoji_Go("Emoji_Go"),
    Emoji_GoodGame("Emoji_GoodGame"),
    Emoji_Headshot("Emoji_Headshot"),
    Emoji_Heartbroken("Emoji_Heartbroken"),
    Emoji_HeartHands("Emoji_HeartHands"),
    Emoji_Hoarder("Emoji_Hoarder"),
    Emoji_HotChocolate("Emoji_HotChocolate"),
    Emoji_HotDawg("Emoji_HotDawg"),
    Emoji_HuskWow("Emoji_HuskWow"),
    Emoji_IceHeart("Emoji_IceHeart"),
    Emoji_InLove("Emoji_InLove"),
    Emoji_ISeeYou("Emoji_ISeeYou"),
    Emoji_Kaboom("Emoji_Kaboom"),
    Emoji_LOL("Emoji_LOL"),
    Emoji_Lucky("Emoji_Lucky"),
    Emoji_Majestic("Emoji_Majestic"),
    Emoji_MaryBobbins("Emoji_MaryBobbins"),
    Emoji_Meet("Emoji_Meet"),
    Emoji_Mistletoe("Emoji_Mistletoe"),
    Emoji_Mittens("Emoji_Mittens"),
    Emoji_MVP("Emoji_MVP"),
    Emoji_Number1("Emoji_Number1"),
    Emoji_OnFire("Emoji_OnFire"),
    Emoji_PeaceSign("Emoji_PeaceSign"),
    Emoji_Penguin("Emoji_Penguin"),
    Emoji_PickAxe("Emoji_PickAxe"),
    Emoji_Pizza("Emoji_Pizza"),
    Emoji_Placeholder("Emoji_Placeholder"),
    Emoji_Plotting("Emoji_Plotting"),
    Emoji_Plunger("Emoji_Plunger"),
    Emoji_PoolParty("Emoji_PoolParty"),
    Emoji_Positivity("Emoji_Positivity"),
    Emoji_PotatoAim("Emoji_PotatoAim"),
    Emoji_Potion("Emoji_Potion"),
    Emoji_PotOfGold("Emoji_PotOfGold"),
    Emoji_Prickly("Emoji_Prickly"),
    Emoji_Rabid("Emoji_Rabid"),
    Emoji_Rage("Emoji_Rage"),
    Emoji_Rainbow("Emoji_Rainbow"),
    Emoji_Rekt("Emoji_Rekt"),
    Emoji_RIP("Emoji_RIP"),
    Emoji_Rock("Emoji_Rock"),
    Emoji_RocketRide("Emoji_RocketRide"),
    Emoji_RockOn("Emoji_RockOn"),
    Emoji_S6Lvl100("Emoji_S6Lvl100"),
    Emoji_S7Lvl100("Emoji_S7Lvl100"),
    Emoji_Salty("Emoji_Salty"),
    Emoji_Snowflake("Emoji_Snowflake"),
    Emoji_Snowman("Emoji_Snowman"),
    Emoji_Stealthy("Emoji_Stealthy"),
    Emoji_Stinky("Emoji_Stinky"),
    Emoji_Stop("Emoji_Stop"),
    Emoji_Storm("Emoji_Storm"),
    Emoji_Sucker("Emoji_Sucker"),
    Emoji_Tasty("Emoji_Tasty"),
    Emoji_Tattered("Emoji_Tattered"),
    Emoji_Teamwork("Emoji_Teamwork"),
    Emoji_Thief("Emoji_Thief"),
    Emoji_ThumbsDown("Emoji_ThumbsDown"),
    Emoji_ThumbsUp("Emoji_ThumbsUp"),
    Emoji_TP("Emoji_TP"),
    Emoji_Trap("Emoji_Trap"),
    Emoji_VictoryRoyale("Emoji_VictoryRoyale"),
    Emoji_WitchsBrew("Emoji_WitchsBrew"),
    Emoji_Wow("Emoji_Wow"),
    Emoji_ZZZ("Emoji_ZZZ");

    private final String name;

    Emoji(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
